name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4

      - name: Run Pytest
        run: |
          uv run pytest -m "not slow" --cov=src/zotero_arxiv_daily --cov-report=term-missing
